// File generated by FlutterFire CLI.
// To use this file, you must run the FlutterFire CLI:
//
// flutterfire configure
//
// This will generate the firebase_options.dart file with your Firebase project configuration.

import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform;
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

class DefaultFirebaseOptions {
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKlIwA3NHVQ9q41JYdOFSuQS0osXG-SJ8',
    appId: '1:479500154623:web:47d904cb0dff6b0c6ffeca',
    messagingSenderId: '479500154623',
    projectId: 'kigali-city-services-91a83',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKlIwA3NHVQ9q41JYdOFSuQS0osXG-SJ8',
    appId: '1:479500154623:android:47d904cb0dff6b0c6ffeca',
    messagingSenderId: '479500154623',
    projectId: 'kigali-city-services-91a83',
    databaseURL: 'https://kigali-city-services-91a83.firebaseio.com',
  );

  static final FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASDPeVVbwnCdtvMZchj-KrtF1mAdcyXSE',
    appId: '1:479500154623:ios:9d6b3bdf835e66bb6ffeca',
    messagingSenderId: '479500154623',
    projectId: 'kigali-city-services-91a83',
    databaseURL: 'https://kigali-city-services-91a83.firebaseio.com',
    iosBundleId: 'com.example.kigaliCityServiced',
  );

  static final FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASDPeVVbwnCdtvMZchj-KrtF1mAdcyXSE',
    appId: '1:479500154623:ios:9d6b3bdf835e66bb6ffeca',
    messagingSenderId: '479500154623',
    projectId: 'kigali-city-services-91a83',
    databaseURL: 'https://kigali-city-services-91a83.firebaseio.com',
    iosBundleId: 'com.example.kigaliCityServiced.macos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKlIwA3NHVQ9q41JYdOFSuQS0osXG-SJ8',
    appId: '1:479500154623:web:47d904cb0dff6b0c6ffeca',
    messagingSenderId: '479500154623',
    projectId: 'kigali-city-services-91a83',
    authDomain: 'kigali-city-services-91a83.firebaseapp.com',
  );

  /// Get platform-specific Firebase options
  static FirebaseOptions get currentPlatform {
    try {
      switch (defaultTargetPlatform) {
        case TargetPlatform.android:
          return android;
        case TargetPlatform.iOS:
          return ios;
        case TargetPlatform.macOS:
          return macos;
        case TargetPlatform.windows:
          return windows;
        case TargetPlatform.linux:
          throw UnsupportedError(
            'DefaultFirebaseOptions have not been configured for linux - run "flutterfire configure" to fix this.',
          );
        case TargetPlatform.fuchsia:
          throw UnsupportedError(
            'DefaultFirebaseOptions have not been configured for fuchsia',
          );
      }
    } catch (e) {
      // Auto-detected platform implementation fallback
      return web;
    }
  }
}
